# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Statistics.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Z_Score import  *
from Pie_Chart import *
from Bar_Chart import *
from Regression import *
from Mean_Median_Mode import *
from Histogram import *
from Population_Mean import *
from Correlation import *
from Box_Plot import *

class Ui_MainWindow(object):
    def openZ_Score(self):
        self.window= QtWidgets.QDialog()
        self.ui=Ui_Z_Score()
        self.ui.setupUi(self.window)
        self.window.show()

    def openRegrssion(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Regression()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPop_Mean(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_PopulationMean()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPie_Chart(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_PieChart()
        self.ui.setupUi(self.window)
        self.window.show()

    def openMMM(self):
        self.window =QtWidgets.QMainWindow()
        self.ui = Ui_Mean_Median_Mode()
        self.ui.setupUi(self.window)
        self.window.show()

    def openHistogram(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Histogram()
        self.ui.setupUi(self.window)
        self.window.show()


    def openCorrelation(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Correlation()
        self.ui.setupUi(self.window)
        self.window.show()

    def openBox_Plot(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Box_plot()
        self.ui.setupUi(self.window)
        self.window.show()

    def openBar_Chart(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_BarChart()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 380, 251, 211))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Pie Chart.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 251, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("meanModeMedian.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 380, 241, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Bar Char.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 0, 731, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1090, 70, 261, 211))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("population mean.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.Btn__MMM = QtWidgets.QPushButton(self.centralwidget)
        self.Btn__MMM.setGeometry(QtCore.QRect(50, 290, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn__MMM.setFont(font)
        self.Btn__MMM.setObjectName("Btn__MMM")
        self.Btn__MMM.clicked.connect(self.openMMM)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 70, 261, 211))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("regression.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.Btn_PieChart = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_PieChart.setGeometry(QtCore.QRect(770, 600, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_PieChart.setFont(font)
        self.Btn_PieChart.setObjectName("Btn_PieChart")
        self.Btn_PieChart.clicked.connect(self.openPie_Chart)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 70, 271, 211))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("correlation.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.Btn_BarChart = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_BarChart.setGeometry(QtCore.QRect(210, 600, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_BarChart.setFont(font)
        self.Btn_BarChart.setObjectName("Btn_BarChart")
        self.Btn_BarChart.clicked.connect(self.openBar_Chart)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(990, 380, 251, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("boxplot4.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.Btn_Histogram = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Histogram.setGeometry(QtCore.QRect(490, 600, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Histogram.setFont(font)
        self.Btn_Histogram.setObjectName("Btn_Histogram")
        self.Btn_Histogram.clicked.connect(self.openHistogram)
        self.Btn_Pop_Mean = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Pop_Mean.setGeometry(QtCore.QRect(1150, 290, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Pop_Mean.setFont(font)
        self.Btn_Pop_Mean.setObjectName("Btn_Pop_Mean")
        self.Btn_Pop_Mean.clicked.connect(self.openPop_Mean)
        self.Btn_BoxPlot = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_BoxPlot.setGeometry(QtCore.QRect(1030, 600, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_BoxPlot.setFont(font)
        self.Btn_BoxPlot.setObjectName("Btn_BoxPlot")
        self.Btn_BoxPlot.clicked.connect(self.openBox_Plot)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 380, 271, 211))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Bar Chart.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.Btn_Regression = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Regression.setGeometry(QtCore.QRect(600, 290, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Regression.setFont(font)
        self.Btn_Regression.setObjectName("Btn_Regression")
        self.Btn_Regression.clicked.connect(self.openRegrssion)
        self.Btn_correlation = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_correlation.setGeometry(QtCore.QRect(340, 290, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_correlation.setFont(font)
        self.Btn_correlation.setObjectName("Btn_correlation")
        self.Btn_correlation.clicked.connect(self.openCorrelation)
        self.Btn_Z_score = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Z_score.setGeometry(QtCore.QRect(880, 290, 158, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Z_score.setFont(font)
        self.Btn_Z_score.setObjectName("Btn_Z_score")
        self.Btn_Z_score.clicked.connect(self.openZ_Score)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(820, 70, 261, 211))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("z score.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose What You Want To Calculate !!"))
        self.Btn__MMM.setText(_translate("MainWindow", "Mean , Median , Mode"))
        self.Btn_PieChart.setText(_translate("MainWindow", "Pie Chart"))
        self.Btn_BarChart.setText(_translate("MainWindow", "Bar Chart"))
        self.Btn_Histogram.setText(_translate("MainWindow", "Histogram"))
        self.Btn_Pop_Mean.setText(_translate("MainWindow", "Population Mean"))
        self.Btn_BoxPlot.setText(_translate("MainWindow", "Box Plot"))
        self.Btn_Regression.setText(_translate("MainWindow", "Regression"))
        self.Btn_correlation.setText(_translate("MainWindow", "Correlation"))
        self.Btn_Z_score.setText(_translate("MainWindow", "Z_Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

